var g=Object.defineProperty;var h=(e,t,o)=>t in e?g(e,t,{enumerable:!0,configurable:!0,writable:!0,value:o}):e[t]=o;var a=(e,t,o)=>(h(e,typeof t!="symbol"?t+"":t,o),o),y=(e,t,o)=>{if(!t.has(e))throw TypeError("Cannot "+o)};var d=(e,t,o)=>(y(e,t,"read from private field"),o?o.call(e):t.get(e)),f=(e,t,o)=>{if(t.has(e))throw TypeError("Cannot add the same private member more than once");t instanceof WeakSet?t.add(e):t.set(e,o)};import{i as m}from"./assets/vendor-ad859c2f.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))n(s);new MutationObserver(s=>{for(const r of s)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function o(s){const r={};return s.integrity&&(r.integrity=s.integrity),s.referrerPolicy&&(r.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?r.credentials="include":s.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(s){if(s.ep)return;s.ep=!0;const r=o(s);fetch(s.href,r)}})();const L="https://pixabay.com/",v="api/",S="44530588-77e4763ebb7280f93ce94dd82",b={};var l;class p{constructor(){a(this,"query","");f(this,l,10);a(this,"page",1);a(this,"total_pages",1)}getArticles(){const t=new URLSearchParams({key:S,q:this.query,image_type:"photo",orientation:"horizontal",safesearch:!0}),o=`${L}${v}?${t}`;return console.log(o),fetch(o,b).then(n=>n.json())}get pageSize(){return d(this,l)}}l=new WeakMap;function E(e){return console.log(e),`<li class="list-el">

 <a href="${e.largeImageURL}"><img src='${e.webformatURL}' alt='${e.tags}'></a>
  <div class="content">
    <div class="item"><h3>Likes</h3><p>${e.likes}</p></div>
    <div class="item"><h3>Views</h3><p>${e.views}</p></div>
    <div class="item"><h3>Comments</h3><p>${e.comments}</p></div>
    <div class="item"><h3>Downloads</h3><p>${e.downloads}</p></div>
 </div>
</li>
`}const c={formElem:document.querySelector(".js-search-form"),articleListElem:document.querySelector(".js-article-list"),btnLoadMore:document.querySelector(".js-btn-load"),loadElem:document.querySelector(".js-loader")},i=new p;c.formElem.addEventListener("submit",P);async function P(e){if(e.preventDefault(),i.query=e.target.elements.query.value.trim(),i.page=1,c.articleListElem.innerHTML="",!(i.query.trim()!=="")){m.error({message:"Info Search input must be filled!"});return}try{const o=await i.getArticles();console.log(o),console.log(o.total),o.total==0&&m.info({title:"Sorry,",message:"there are no images matching your search query. Please try again!"}),i.totalResult=o.totalResults,w(o.hits)}catch(o){i.totalResult=0,m.error({title:"Error1",message:o.message})}A()}function q(e){return e.map(E).join("")}function w(e){const t=q(e);c.articleListElem.insertAdjacentHTML("beforeend",t)}function A(){console.log(i.totalResult),console.log(i.page),Math.ceil(i.totalResult/p.PAGE_SIZE)<=i.page&&c.btnLoadMore.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
