var g=Object.defineProperty;var L=(e,t,r)=>t in e?g(e,t,{enumerable:!0,configurable:!0,writable:!0,value:r}):e[t]=r;var a=(e,t,r)=>(L(e,typeof t!="symbol"?t+"":t,r),r),v=(e,t,r)=>{if(!t.has(e))throw TypeError("Cannot "+r)};var f=(e,t,r)=>(v(e,t,"read from private field"),r?r.call(e):t.get(e)),p=(e,t,r)=>{if(t.has(e))throw TypeError("Cannot add the same private member more than once");t instanceof WeakSet?t.add(e):t.set(e,r)};import{S as h,i as d}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))n(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function r(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(s){if(s.ep)return;s.ep=!0;const o=r(s);fetch(s.href,o)}})();const S="https://pixabay.com/",b="api/",w="44530588-77e4763ebb7280f93ce94dd82",q={};var c;class E{constructor(){a(this,"query","");p(this,c,10);a(this,"page",1);a(this,"total_pages",1)}getArticles(){const t=new URLSearchParams({key:w,q:this.query,image_type:"photo",orientation:"horizontal",safesearch:!0}),r=`${S}${b}?${t}`;return console.log(r),fetch(r,q).then(n=>n.json())}get pageSize(){return f(this,c)}}c=new WeakMap;function A(e){return console.log(e),`<li class="list-el">

 <a href="${e.largeImageURL}"><img src='${e.webformatURL}' alt='${e.tags}'></a>
  <div class="content">
    <div class="item"><h3>Likes</h3><p>${e.likes}</p></div>
    <div class="item"><h3>Views</h3><p>${e.views}</p></div>
    <div class="item"><h3>Comments</h3><p>${e.comments}</p></div>
    <div class="item"><h3>Downloads</h3><p>${e.downloads}</p></div>
 </div>
</li>
`}let $=new h(".gallery a");const y=document.querySelector(".loader");l();const m={formElem:document.querySelector(".js-search-form"),articleListElem:document.querySelector(".js-article-list"),btnLoadMore:document.querySelector(".js-btn-load"),loadElem:document.querySelector(".js-loader")},i=new E;m.formElem.addEventListener("submit",P);async function P(e){if(e.preventDefault(),O(),i.query=e.target.elements.query.value.trim(),i.page=1,m.articleListElem.innerHTML="",!(i.query.trim()!=="")){l(),d.error({message:"Info Search input must be filled!"});return}try{const r=await i.getArticles();l(),r.total==0&&d.info({title:"Sorry,",message:"there are no images matching your search query. Please try again!"}),i.totalResult=r.totalResults,j(r.hits)}catch(r){i.totalResult=0,d.error({title:"Error1",message:r.message})}l()}function R(e){return e.map(A).join("")}function j(e){const t=R(e);m.articleListElem.insertAdjacentHTML("beforeend",t),$.refresh()}function O(){y.classList.remove("visually-hidden")}function l(){y.classList.add("visually-hidden")}new h(".gallery a",{captionDelay:250,captionsData:"alt"});
//# sourceMappingURL=commonHelpers.js.map
